[package]
name = "netlink_wi"
version = "0.3.0"
authors = [
    "Olli Paakkunainen <olli@paakkunainen.fi>",
    "Adarsh Krishnan <adarshk7@gmail.com>",
]
edition = "2021"
description = """
A library and command-line utility to retrieve information about wireless interfaces
in Linux operating system using netlink protocol.
"""
categories = ["command-line-utilities"]
keywords = ["netlink", "linux", "wifi", "nl80211"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/uption/netlink_wi"
exclude = [".github/*"]

[lib]
name = "netlink_wi"
path = "src/lib.rs"

[dependencies]
neli = "0.6.3"
neli-proc-macros = "0.1.3"
