[package]
name = "netlink_wi"
version = "0.1.0"
authors = ["Olli Paakkunainen <olli@paakkunainen.fi>"]
edition = "2018"
description = """
A library and command-line utility to retrieve information about wireless interfaces
in Linux operating system using netlink protocol.
"""
categories = ["command-line-utilities"]
keywords = ["netlink", "linux", "wifi", "nl80211"]
license = "MIT"
readme = "README.md"
documentation = "https://github.com/uption/netlink-wi"
repository = "https://github.com/uption/netlink-wi"
homepage = "https://github.com/uption/netlink-wi"
exclude = [".github/*"]

[lib]
name = "netlink_wi"
path = "src/lib.rs"

[[bin]]
name = "netlink_wi_cmd"
path = "src/cmd/main.rs"

[dependencies]
neli = "0.4.4"
