name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    name: Build crate and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache cargo
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5

      - name: Build
        run: cargo build --all-features --locked

      - name: Run unit tests
        run: cargo test --all-features

  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clippy
        run: rustup component add clippy

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  format:
    name: Run formatter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  block-autosquash-commits:
    name: Block autosquash commits
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Block autosquash commits
        uses: xt0rted/block-autosquash-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
